# Generated by Django 5.2.7 on 2025-10-10 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('contacto', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Venta', 'Venta'), ('Intercambio', 'Intercambio'), ('Donación', 'Donación')], default='Donación', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
