# Generated by Django 5.2.7 on 2025-10-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookityApp', '0003_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='latitud_defecto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='longitud_defecto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
