# Generated by Django 5.2.7 on 2025-10-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookityApp', '0004_alter_perfil_latitud_defecto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-fecha_comentario']},
        ),
        migrations.AddField(
            model_name='perfil',
            name='nivel_usuario',
            field=models.IntegerField(default=0),
        ),
    ]
