# Generated by Django 5.2.7 on 2025-10-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookityApp', '0005_alter_comentario_options_perfil_nivel_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Cerrado', 'Cerrado')], default='Disponible', max_length=20),
        ),
    ]
