# Generated by Django 5.2.7 on 2025-10-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookityApp', '0007_publicacion_trato_cerrado_con'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='puntaje_usuario',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nivel_usuario',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Medio', 'Medio'), ('KPro', 'KPro')], default='Nuevo', max_length=20),
        ),
    ]
