# Generated by Django 5.2.7 on 2025-11-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookityApp', '0008_perfil_puntaje_usuario_alter_perfil_nivel_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='latitud_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='longitud_temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
