# Generated by Django 5.2.7 on 2025-11-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookityApp', '0009_perfil_latitud_temp_perfil_longitud_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='latitud_temp',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='longitud_temp',
        ),
    ]
