# Generated by Django 5.2.7 on 2025-11-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookityApp', '0010_remove_perfil_latitud_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='calificación',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
