# Generated by Django 5.2.7 on 2025-11-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookityApp', '0011_publicacion_calificación'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='calificación',
            new_name='calificacion',
        ),
    ]
