# Generated by Django 5.2.7 on 2025-11-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookityApp', '0012_rename_calificación_publicacion_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='promedio_calificaciones',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='resena',
            field=models.TextField(blank=True, null=True),
        ),
    ]
