# Generated by Django 5.2.7 on 2025-11-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookityApp', '0013_perfil_promedio_calificaciones_publicacion_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='radio_marcador',
            field=models.FloatField(default=50),
        ),
    ]
