# Generated by Django 5.2.7 on 2025-11-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookityApp', '0014_publicacion_radio_marcador'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='radio_marcador_defecto',
            field=models.FloatField(default=50),
        ),
    ]
