# Generated by Django 5.2.7 on 2025-11-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookityApp', '0016_perfil_usuarios_seguidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='usuarios_seguidos',
            field=models.ManyToManyField(blank=True, related_name='seguidores', to='BookityApp.perfil'),
        ),
    ]
