# Generated by Django 5.2.8 on 2025-11-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookityApp', '0017_alter_perfil_usuarios_seguidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='usuarios_seguidos',
            field=models.ManyToManyField(blank=True, to='BookityApp.perfil'),
        ),
    ]
