# Generated by Django 5.2.7 on 2025-11-11 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookityApp', '0018_alter_perfil_usuarios_seguidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('otro_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookityApp.perfil')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='BookityApp.perfil')),
            ],
        ),
    ]
