# Generated by Django 5.2.7 on 2025-11-11 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookityApp', '0019_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='otro_perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BookityApp.perfil'),
        ),
    ]
