# Generated by Django 5.2.7 on 2025-11-15 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookityApp', '0020_alter_notificacion_otro_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cara', models.IntegerField(default=1)),
                ('ojos', models.IntegerField(default=1)),
                ('ceja', models.IntegerField(default=1)),
                ('boca', models.IntegerField(default=1)),
                ('patilla', models.IntegerField(default=1)),
                ('oreja', models.IntegerField(default=1)),
                ('chasquilla', models.IntegerField(default=1)),
                ('peloatras', models.IntegerField(default=1)),
                ('pelonuca', models.IntegerField(default=1)),
                ('polera', models.IntegerField(default=1)),
                ('chaqueta', models.IntegerField(default=1)),
                ('tatu', models.IntegerField(default=1)),
                ('back', models.IntegerField(default=1)),
                ('cuerpo', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
